sudo: required
dist: trusty

language: generic

services:
  - docker

before_install:
  - docker pull nickg/libinjection-docker

script:
  - docker run -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -v $HOME/build/client9/libinjection:/build -w /build nickg/libinjection-docker ./make-ci.sh

