pipeline {
    agent { label 'debian-builder' }
    stages {
        stage('build') {
            steps {
                sh 'gbp buildpackage --git-export-dir=./build'
            }
        }
    }
}
